<?php

namespace App\Filament\Layanankkprl\Resources\Services\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class ServiceForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->label('Nama Layanan')
                    ->required(),
                \Filament\Forms\Components\Textarea::make('description')
                    ->label('Deskripsi')
                    ->rows(3)
                    ->columnSpanFull(),
                // Slug is auto-generated by Model event
                Toggle::make('is_active')
                    ->label('Status Aktif')
                    ->default(true)
                    ->required(),
                Toggle::make('requires_documents')
                    ->label('Wajib Upload Dokumen?')
                    ->helperText('Jika aktif, pemohon wajib upload dokumen pendukung saat reservasi.')
                    ->default(false),
            ]);
    }
}
